version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing frontend dependencies...
      - cd front
      - npm install

  build:
    commands:
      - echo Building the React frontend...
      - npm run build

artifacts:
  base-directory: front/dist
  files:
    - '**/*'
